# Generated by Django 5.2.1 on 2025-06-14 23:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('funcionarios', '0004_alter_funcionario_ativo_alter_funcionario_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='funcionario',
            name='cpf',
        ),
    ]
