# Generated by Django 5.2.1 on 2025-07-03 16:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('funcionarios', '0005_remove_funcionario_cpf'),
        ('ocorrencias', '0004_alter_ocorrencia_registrado_por'),
        ('reservas', '0004_alter_checkincheckout_funcionario_checkin_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='funcionario',
            name='cargo',
        ),
        migrations.DeleteModel(
            name='Cargo',
        ),
        migrations.DeleteModel(
            name='Funcionario',
        ),
    ]
