# Generated by Django 5.2 on 2025-07-04 13:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('funcionarios', '0006_remove_funcionario_cargo_delete_cargo_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cargo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_funcao', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Funcionario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
                ('ativo', models.BooleanField(default=True)),
                ('email', models.EmailField(max_length=254)),
                ('cargo', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='funcionarios.cargo')),
            ],
        ),
    ]
