# Generated by Django 5.2 on 2025-07-04 16:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('funcionarios', '0007_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='funcionario',
            name='cargo',
        ),
        migrations.DeleteModel(
            name='Cargo',
        ),
        migrations.DeleteModel(
            name='Funcionario',
        ),
    ]
