# Generated by Django 5.1.7 on 2025-04-28 23:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("funcionarios", "0001_initial"),
        ("quartos", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Ocorrencia",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("descricao", models.TextField()),
                ("data_registro", models.DateField()),
                ("resolvido", models.BooleanField(default=False)),
                (
                    "quarto",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="quartos.quarto"
                    ),
                ),
                (
                    "registrado_por",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.RESTRICT,
                        to="funcionarios.funcionario",
                    ),
                ),
            ],
        ),
    ]
