# Generated by Django 5.2.1 on 2025-06-11 23:56

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ocorrencias', '0001_initial'),
        ('quartos', '0002_alter_quarto_tipo'),
    ]

    operations = [
        migrations.AddField(
            model_name='ocorrencia',
            name='data_resolvido',
            field=models.DateTimeField(default=datetime.datetime(2025, 6, 11, 23, 56, 43, 326270, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='ocorrencia',
            name='quarto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='quartos.quarto'),
        ),
    ]
