# Generated by Django 5.2.1 on 2025-06-11 23:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ocorrencias', '0002_ocorrencia_data_resolvido_alter_ocorrencia_quarto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ocorrencia',
            name='data_resolvido',
            field=models.DateTimeField(null=True),
        ),
    ]
