# Generated by Django 5.2 on 2025-07-04 13:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('funcionarios', '0007_initial'),
        ('ocorrencias', '0004_alter_ocorrencia_registrado_por'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ocorrencia',
            name='data_registro',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='ocorrencia',
            name='data_resolvido',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='ocorrencia',
            name='registrado_por',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='funcionarios.funcionario'),
        ),
    ]
