# Generated by Django 5.2 on 2025-07-04 13:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ocorrencias', '0005_alter_ocorrencia_data_registro_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ocorrencia',
            name='registrado_por',
        ),
    ]
