# Generated by Django 5.2.1 on 2025-06-14 23:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0003_alter_cliente_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='cep',
            field=models.CharField(default=95690000, max_length=8),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cliente',
            name='cpf',
            field=models.CharField(default=99999999999, max_length=11, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cliente',
            name='endereco',
            field=models.CharField(default='Rua Teste, 20', max_length=50, verbose_name='Endereço'),
            preserve_default=False,
        ),
    ]
