# Generated by Django 5.2.1 on 2025-07-07 00:36

import django.db.models.deletion
import stdimage.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TipoQuarto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, unique=True)),
                ('descricao', models.TextField(blank=True, max_length=400, null=True)),
                ('capacidade', models.IntegerField(verbose_name='Capacidade')),
            ],
        ),
        migrations.CreateModel(
            name='Quarto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.IntegerField(unique=True, verbose_name='Número do Quarto')),
                ('andar', models.IntegerField(verbose_name='Andar do Quarto')),
                ('descricao', models.TextField(blank=True, null=True, verbose_name='Descrição do Quarto')),
                ('status', models.CharField(choices=[('disponivel', 'Disponível'), ('ocupado', 'Ocupado'), ('manutencao', 'Em Manutenção'), ('reservado', 'Reservado'), ('indisponivel', 'Indisponível')], max_length=25, verbose_name='Status Atual')),
                ('foto', stdimage.models.StdImageField(blank=True, force_min_size=False, null=True, upload_to='fotos/quartos', variations={'large': (600, 400), 'medium': (300, 300), 'thumb': (150, 150)})),
                ('tipo', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='quartos.tipoquarto', verbose_name='Tipo de Quarto')),
            ],
        ),
    ]
