# Generated by Django 5.2.1 on 2025-06-11 23:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quartos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quarto',
            name='tipo',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, to='quartos.tipoquarto', verbose_name='Tipo de Quarto'),
        ),
    ]
