# Generated by Django 5.2.1 on 2025-06-12 00:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quartos', '0002_alter_quarto_tipo'),
    ]

    operations = [
        migrations.AddField(
            model_name='statusquarto',
            name='descricao',
            field=models.TextField(max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='tipoquarto',
            name='banheiras',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='tipoquarto',
            name='quantidade_camas',
            field=models.IntegerField(default=1),
        ),
    ]
