# Generated by Django 5.2.1 on 2025-06-12 00:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quartos', '0003_statusquarto_descricao_tipoquarto_banheiras_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tipoquarto',
            name='banheiras',
        ),
        migrations.RemoveField(
            model_name='tipoquarto',
            name='quantidade_camas',
        ),
        migrations.AddField(
            model_name='quarto',
            name='descricao',
            field=models.TextField(blank=True, null=True, verbose_name='Descrição'),
        ),
        migrations.AddField(
            model_name='tipoquarto',
            name='descricao',
            field=models.TextField(blank=True, max_length=250, null=True),
        ),
    ]
