# Generated by Django 5.2.1 on 2025-06-12 00:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quartos', '0004_remove_tipoquarto_banheiras_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quarto',
            name='capacidade',
        ),
        migrations.AddField(
            model_name='quarto',
            name='andar',
            field=models.IntegerField(blank=True, null=True, verbose_name='Andar'),
        ),
        migrations.AddField(
            model_name='tipoquarto',
            name='banheiras',
            field=models.BooleanField(default=False, help_text='Tem banheiras', verbose_name='Banheiras'),
        ),
        migrations.AddField(
            model_name='tipoquarto',
            name='capacidade',
            field=models.IntegerField(default=1, verbose_name='Capacidade'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tipoquarto',
            name='possui_varanda',
            field=models.BooleanField(default=False, verbose_name='Possui Varanda'),
        ),
        migrations.AddField(
            model_name='tipoquarto',
            name='quantidade_camas',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='tipoquarto',
            name='descricao',
            field=models.TextField(blank=True, max_length=400, null=True),
        ),
    ]
