# Generated by Django 5.2.1 on 2025-06-16 23:21

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quartos', '0005_remove_quarto_capacidade_quarto_andar_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quarto',
            name='andar',
            field=models.IntegerField(
                default=1, verbose_name='Andar do Quarto'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='quarto',
            name='descricao',
            field=models.TextField(blank=True, null=True,
                                   verbose_name='Descrição do Quarto'),
        ),
        migrations.AlterField(
            model_name='quarto',
            name='status',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT,
                                    to='quartos.statusquarto', verbose_name='Status Atual'),
        ),
        migrations.AlterField(
            model_name='quarto',
            name='tipo',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.RESTRICT,
                                    to='quartos.tipoquarto', verbose_name='Tipo de Quarto'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='statusquarto',
            name='descricao',
            field=models.TextField(blank=True, max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='tipoquarto',
            name='banheiras',
            field=models.BooleanField(
                default=False, help_text='O quarto possui banheiras?', verbose_name='Tem Banheiras'),
        ),
        migrations.AlterField(
            model_name='tipoquarto',
            name='quantidade_camas',
            field=models.IntegerField(
                default=1, verbose_name='Quantidade de Camas'),
        ),
    ]
