# Generated by Django 5.2.1 on 2025-06-16 23:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quartos', '0006_alter_quarto_andar_alter_quarto_descricao_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tipoquarto',
            name='quantidade_camas',
        ),
    ]
