# Generated by Django 5.2.1 on 2025-06-18 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quartos', '0007_remove_tipoquarto_quantidade_camas'),
    ]

    operations = [
        migrations.AlterField(
            model_name='statusquarto',
            name='descricao',
            field=models.TextField(blank=True, max_length=256, null=True, verbose_name='Descrição'),
        ),
    ]
