# Generated by Django 5.2.1 on 2025-07-02 22:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quartos', '0008_alter_statusquarto_descricao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quarto',
            name='status',
            field=models.CharField(choices=[('disponivel', 'Disponível'), ('ocupado', 'Ocupado'), ('manutencao', 'Em Manutenção'), ('indisponivel', 'Indisponível')], max_length=25, verbose_name='Status Atual'),
        ),
        migrations.RemoveField(
            model_name='tipoquarto',
            name='banheiras',
        ),
        migrations.RemoveField(
            model_name='tipoquarto',
            name='possui_varanda',
        ),
        migrations.DeleteModel(
            name='StatusQuarto',
        ),
    ]
