# Generated by Django 5.2.1 on 2025-07-05 14:31

import stdimage.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quartos', '0009_alter_quarto_status_remove_tipoquarto_banheiras_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='quarto',
            name='foto',
            field=stdimage.models.StdImageField(blank=True, force_min_size=False, null=True, upload_to='fotos/quartos', variations={'medium': (300, 300), 'thumb': (150, 150)}),
        ),
    ]
