# Generated by Django 5.2.1 on 2025-07-05 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quartos', '0010_quarto_foto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quarto',
            name='status',
            field=models.CharField(choices=[('disponivel', 'Disponível'), ('ocupado', 'Ocupado'), ('manutencao', 'Em Manutenção'), ('reservado', 'Reservado')], max_length=25, verbose_name='Status Atual'),
        ),
    ]
