# Generated by Django 5.2.1 on 2025-07-07 00:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clientes', '0001_initial'),
        ('quartos', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Reserva',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_entrada', models.DateField()),
                ('data_saida', models.DateField()),
                ('criada_em', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('criada', 'Criada'), ('em_andamento', 'Em Andamento'), ('finalizada', 'Finalizada'), ('cancelada', 'Cancelada')], default='criada', max_length=20)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='clientes.cliente')),
                ('funcionario', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to=settings.AUTH_USER_MODEL)),
                ('quarto', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='quartos.quarto')),
            ],
        ),
        migrations.CreateModel(
            name='CheckInCheckOut',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_checkin', models.DateTimeField()),
                ('data_checkout', models.DateTimeField(null=True)),
                ('funcionario_checkin', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='checkins_realizados', to=settings.AUTH_USER_MODEL)),
                ('funcionario_checkout', models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='checkouts_realizados', to=settings.AUTH_USER_MODEL)),
                ('reserva', models.OneToOneField(on_delete=django.db.models.deletion.RESTRICT, to='reservas.reserva')),
            ],
        ),
    ]
