# Generated by Django 5.2.1 on 2025-06-11 23:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0001_initial'),
        ('funcionarios', '0003_alter_funcionario_cargo'),
        ('quartos', '0002_alter_quarto_tipo'),
        ('reservas', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reserva',
            name='status',
            field=models.CharField(choices=[('criada', 'Criada'), ('em_andamento', 'Em Andamento'), ('finalizada', 'Finalizada'), ('cancelada', 'Cancelada')], default='criada', max_length=20),
        ),
        migrations.AlterField(
            model_name='checkincheckout',
            name='funcionario_checkout',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='checkouts_realizados', to='funcionarios.funcionario'),
        ),
        migrations.AlterField(
            model_name='checkincheckout',
            name='reserva',
            field=models.OneToOneField(on_delete=django.db.models.deletion.RESTRICT, to='reservas.reserva'),
        ),
        migrations.AlterField(
            model_name='reserva',
            name='cliente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='clientes.cliente'),
        ),
        migrations.AlterField(
            model_name='reserva',
            name='quarto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='quartos.quarto'),
        ),
        migrations.DeleteModel(
            name='StatusReserva',
        ),
    ]
