# Generated by Django 5.2.1 on 2025-06-18 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservas', '0002_alter_reserva_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='reserva',
            name='ativa',
            field=models.BooleanField(default=True),
        ),
    ]
