# Generated by Django 5.2.1 on 2025-07-03 16:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservas', '0003_reserva_ativa'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='checkincheckout',
            name='funcionario_checkin',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='checkins_realizados', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='checkincheckout',
            name='funcionario_checkout',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='checkouts_realizados', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='reserva',
            name='funcionario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to=settings.AUTH_USER_MODEL),
        ),
    ]
