# Generated by Django 5.2.1 on 2025-07-04 16:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reservas', '0004_alter_checkincheckout_funcionario_checkin_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reserva',
            name='ativa',
        ),
    ]
