# Generated by Django 5.2.1 on 2025-07-07 00:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('quartos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tarifa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor', models.DecimalField(decimal_places=2, max_digits=8)),
                ('temporada', models.CharField(blank=True, choices=[('Baixa', 'Baixa Temporada'), ('Média', 'Média Temporada'), ('Alta', 'Alta Temporada')], max_length=10, null=True)),
                ('ativa', models.BooleanField(default=True)),
                ('data_inicio', models.DateField()),
                ('data_fim', models.DateField()),
                ('tipo_quarto', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='quartos.tipoquarto')),
            ],
        ),
    ]
