# Generated by Django 5.1.7 on 2025-04-28 23:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("quartos", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Temporada",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name="Tarifa",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("valor", models.DecimalField(decimal_places=2, max_digits=8)),
                ("ativa", models.BooleanField(default=True)),
                ("data_inicio", models.DateField()),
                ("data_fim", models.DateField()),
                (
                    "tipo_quarto",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.RESTRICT,
                        to="quartos.tipoquarto",
                    ),
                ),
                (
                    "temporada",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="tarifas.temporada",
                    ),
                ),
            ],
        ),
    ]
