# Generated by Django 5.2.1 on 2025-06-12 00:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tarifas', '0002_alter_tarifa_temporada'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tarifa',
            name='temporada',
            field=models.CharField(blank=True, choices=[('Baixa', 'Baixa Temporada'), ('Média', 'Média Temporada'), ('Alta', 'Alta Temporada')], max_length=10, null=True),
        ),
        migrations.DeleteModel(
            name='Temporada',
        ),
    ]
